function save_TIRadar_pcd(output_pcd_path, pcd_data)
    fid = fopen(output_pcd_path, "w");
    fprintf(fid, "VERSION .7\n" + ...
        "FIELDS x y z velocity range intensity noise snr\n" + ...
        "SIZE 4 4 4 4 4 4 4 4\n" + ...
        "TYPE F F F F F F F F\n" + ...
        "COUNT 1 1 1 1 1 1 1 1\n" + ...
        "WIDTH %d\n" + ...
        "HEIGHT 1\n" + ...
        "VIEWPOINT 0 0 0 1 0 0 0\n" + ...
        "POINTS %d\n" + ...
        "DATA ascii", size(pcd_data, 1), size(pcd_data, 1));
    fclose(fid);
    writematrix(pcd_data, output_pcd_path, "FileType", "text", "WriteMode", "append","Delimiter", " ");
end